#pragma once

#include "external_def.h"

typedef enum
{
 EFI_STATUS_EFI_TEXT_SET_CURSOR_POSITION_EFI_SUCCESS,
 EFI_STATUS_EFI_TEXT_SET_CURSOR_POSITION_EFI_DEVICE_ERROR,
 EFI_STATUS_EFI_TEXT_SET_CURSOR_POSITION_EFI_UNSUPPORTED,
}EFI_STATUS_EFI_TEXT_SET_CURSOR_POSITION;

typedef EFI_STATUS_EFI_TEXT_SET_CURSOR_POSITION (*EFI_TEXT_SET_CURSOR_POSITION) (
    EFI_SIMPLE_TEXT_OUTPUT_PROTOCOL *This,
    UINTN Column,
    UINTN Row);
