#include "efi/efi.h"

typedef enum
{
 EFI_STATUS_MAIN_EFI_SUCCES,
 EFI_STATUS_MAIN_EFI_OUT_OF_RESOURCES,
}EFI_STATUS_MAIN;
EFI_STATUS_MAIN EfiMain (EFI_HANDLE ImageHandle, EFI_SYSTEM_TABLE *SystemTable)
{
  return EFI_STATUS_MAIN_EFI_SUCCES; 
}
